# Generated by Django 2.1.7 on 2019-05-08 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190508_1400'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Formacao',
        ),
        migrations.DeleteModel(
            name='Profissao',
        ),
    ]
