# Generated by Django 2.1.7 on 2019-05-08 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_formacao_profissao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Formacao',
        ),
        migrations.DeleteModel(
            name='Profissao',
        ),
    ]
