# Generated by Django 2.1.7 on 2019-05-16 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_projeto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='image',
            field=models.ImageField(upload_to='projetos/'),
        ),
    ]
