# Generated by Django 2.1.7 on 2019-05-16 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190515_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='image',
            field=models.ImageField(upload_to='../static/imagens'),
        ),
    ]
