# Generated by Django 2.1.7 on 2019-05-16 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_contato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='city',
            field=models.CharField(max_length=25),
        ),
    ]
