# Generated by Django 2.1.7 on 2019-05-16 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20190516_0020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contato',
            old_name='parents',
            new_name='country',
        ),
    ]
